### ISSUE TITLE
useDebounce isn't working as expected on editor state change

### ISSUE THREAD

**Issue by USergei** [USergei/bootcamp#40]
For some reason current implementation of editor's state reader doesn't play well with [useDebounce](https://github.com/xnimorz/use-debounce) 
This may be related to synthetic events in React, https://stackoverflow.com/questions/67143345/usedebounce-hook-doesnt-allow-me-to-type
On the other hand they mention that it's related only to React v16 or lower, so it can be something else.

**Comment by fructusmortus** [comment]
We decided to use custom Debounce implementation, as it it enough for us at the moment.
