### ISSUE TITLE
Creating/editing documents

### ISSUE THREAD

**Issue by USergei** [USergei/bootcamp#47]
At the moment whenever user types something in the document title input or the text editor a new document is created in a database every time. This obviously isn't the way it meant to work. The flow should be as follows: 
- If user is on a document edit page and document title and content is empty, it means that user wants to create a new document. 
-- Whenever user types something in the document title, a new record should be created in a database, endpoint should return an `ID` of new record
-- Then document transitions into editing mode, since we already have a record in a database and we know the `ID`
-- Url should change from `document/new` to `document/<document-id>`
-- If user starts to type in the text editor itself, but leaves the document title input blank, save the document in the database and populate title field as `Untitled document`. The rest of the flow is the same as above.

**Comment by fructusmortus** [comment]
Fixed.
